version: '3.8'
services:
  mysql-microservice:
    image: mysql:8.0.33
    container_name: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_USER: hainh
      MYSQL_PASSWORD: Admin123
      MYSQL_ROOT_PASSWORD: Admin123
      MYSQL_DATABASE: testdata