server:
  port: 8082
## DATABASE CONFIG
spring:
  datasource:
    username: ${DB_USERNAME:root}
    password: ${DB_PW:Admin123}
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:testdata}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  ### EMAIL CONFIG
  mail:
    port: 465
    host:
    password:
    username:
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth:true
        starttls:
          enable: true
          required: true
        ssl:
          enable: true

  #### KAFKA CONFIG
  kafka:
    bootstrap-servers: localhost:19092
    consumer:
      group-id: otp-group-id
      auto-offset-reset: earliest
      enable-auto-commit: true

#####
email:
  from: anonystick@gmail.com