server:
  port: 1122

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:10.56.66.54}:${DB_PORT:3306}/${DB_NAME:testdata}
    username: ${DB_USERNAME:root}
    password: ${DB_PW:Admin123}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  data:
    redis:
      host: 10.56.66.54
      port: 6379
