server:
  port: 1122
  tomcat:
    threads:
      max: 10 #

resilience4j:
  circuitbreaker:
    configs:
      checkRandom:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        #        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10

  ratelimiter:
    instances:
      backendA:
        limitForPeriod: 2 # toi da 10 request/1s
        limitRefreshPeriod: 10s # khoang thoi gian lam moi
        timeoutDuration: 0 # thoi gian cho khi he thong day
        registerHealthIndicator: true
        eventConsumerBufferSize: 100 # bo nho dem
      backendB:
        limitForPeriod: 5
        limitRefreshPeriod: 10s
        timeoutDuration: 3s
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:vetautet}
    username: ${DB_USERNAME:root}
    password: ${DB_PW:Admin123}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  jackson:
    serialization:
      indent-output: true
  ## Redis server connect settings
  data:
    redis:
      host: localhost
      port: 6379
      password: ""
      lettuce:
        pool: # Connection pool settings
          max-active: 8 # Maximum number of active connections in the pool( user 01 for no limit)
          max-idle: 8 # Maximum number of idle connections in the pool
          min-idle: 0 # Minimum number of idle connections in the pool
          max-wait: -1ms # Maximum wait time to get a connections from the pool(user -1 for no limit)
      connect-timeout: 30000